name: Run E2E Tests
on: [pull_request]
runs-on: ubuntu-latest

services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    env:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: 'npm'

  - run: |
      cd node/03-api-solid
      npm ci

  - name: Run tests
    working-directory: node/03-api-solid
    run: npm run test:e2e
    env:
      JWT_SECRET: test
      DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
