name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout Codigo
      uses: actions/checkout@v3

      - name: Instalar dependencias
      run: | 
        cd node/03-api-solid
        npm ci
      - name: Executar testes
      working-directory: node/03-api-solid
      run: npm run test:e2e